### PR TITLE
switch to german movie trailers

### PR DESCRIPTION
**Pull request by nokodemus**
We could / probably should switch to german trailers as there's mainly german-speaking community ...

### CODE REVIEW

**Comment by Kr1ss-XD** [comment]
Since I use library integration, I did actually never recognize that the trailers were in og language 😄 so thx

Will make this dependent on the user's setting for provider language later, though

**Comment by nokodemus** [comment]
Aaah, i see ... no prob ... j
i just thought about it a while, finally looked into trailer.py and luckily the necessary edit was a 1-liner and therefore simple enough ^^

A setting dependency sounds great. But i think there could be a problem with dependency of the set provider language, as you're able to set both, english and german.

Didn't you mean to make the trailer language dependent from information-language?

Greets and keep up the great work :+1:

**Comment by Kr1ss-XD** [comment]
Provider language would work as well : if German is one of the provider languages, search for German trailers, otherwise whish trailers.
Agree that info language fits better though :) cheers

**Comment by nokodemus** [comment]
Alright, the plan in general is absolutely nice ... i guess you know best how to ideally implement it.

**Comment by Kr1ss-XD** [comment]
Yep go ahead

**Pull request merged**
